[package]
name = "qfdrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
rand_distr = "0.5.0-alpha.1"
rayon = "1.10.0"
rustms = { git = "https://github.com/theGreatHerrLebert/rustims.git" }
itertools = "0.12.1"
serde = { version = "1.0.201", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.117"