[package]
name = "sagepy-connector"
version = "0.2.6"
edition = "2021"

[lib]
name = "sagepy_connector"
crate-type = ["cdylib"]

[dependencies]
sage-core = { git = "https://github.com/lazear/sage.git" }
pyo3 = { version = "0.20.0", features = ["extension-module"] }
numpy = "0.20.0"
rayon = "1.8.0"

regex = "1.10.2"
serde = { version = "1.0.190", features = ["derive"] }
log = "0.4.20"
