[package]
name = "sagepy-connector"
version = "0.2.9"
edition = "2021"

[lib]
name = "sagepy_connector"
crate-type = ["cdylib"]

[dependencies]
sage-core = { git = "https://github.com/lazear/sage.git" }
qfdrust = { path  = "../qfdrust" }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
numpy = "0.21.0"
rayon = "1.10.0"

regex = "1.10.4"
serde = { version = "1.0.201", features = ["derive"] }
log = "0.4.21"
itertools = "0.12.1"
serde_json = "1.0.117"