name: Build and Publish Rust Binding

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ['3.10', '3.11', '3.12']
        include:
        - os: ubuntu-latest
          python-version: '3.10'
          publish: true
        - os: windows-latest
          python-version: '3.10'
          publish: true
        - os: macos-13
          python-version: '3.10'
          publish: true
        - os: ubuntu-latest
          python-version: '3.11'
          publish: true
        - os: windows-latest
          python-version: '3.11'
          publish: true
        - os: macos-13
          python-version: '3.11'
          publish: true
        - os: ubuntu-latest
          python-version: '3.12'
          publish: true
        - os: windows-latest
          python-version: '3.12'
          publish: true
        - os: macos-13
          python-version: '3.12'
          publish: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Change to sagepy-connector directory
        run: cd sagepy-connector

      - name: Build sagepy-connector package
        run: |
          cd sagepy-connector
          maturin build --release

      - name: Build sagepy package
        run: |
          cd ../sagepy
          pip install .
