name: Build and Publish Rust Binding

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ['3.10', '3.11', '3.12']
        include:
        - os: ubuntu-latest
          python-version: '3.10'
          publish: true
        - os: windows-latest
          python-version: '3.10'
          publish: true
        - os: macos-13
          python-version: '3.10'
          publish: true
        - os: ubuntu-latest
          python-version: '3.11'
          publish: true
        - os: windows-latest
          python-version: '3.11'
          publish: true
        - os: macos-13
          python-version: '3.11'
          publish: true
        - os: ubuntu-latest
          python-version: '3.12'
          publish: true
        - os: windows-latest
          python-version: '3.12'
          publish: true
        - os: macos-13
          python-version: '3.12'
          publish: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Change to sagepy-connector directory
        run: cd sagepy-connector

      - name: Build sagepy-connector package
        run: |
          cd sagepy-connector
          maturin build --release

      - name: Upload sagepy-connector wheel
        uses: actions/upload-artifact@v3
        with:
          name: sagepy-connector-wheel-${{ matrix.os }}-${{ matrix.python-version }}
          path: sagepy-connector/target/wheels/*.whl

      - name: Build sagepy package
        run: |
          cd sagepy
          pip install .

      - name: Upload sagepy wheel
        uses: actions/upload-artifact@v3
        with:
          name: sagepy-wheel-${{ matrix.os }}-${{ matrix.python-version }}
          path: sagepy/dist/*.whl

  release:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Download sagepy-connector wheels
        uses: actions/download-artifact@v3
        with:
          name: sagepy-connector-wheel-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Download sagepy wheels
        uses: actions/download-artifact@v3
        with:
          name: sagepy-wheel-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sagepy-connector-wheel-${{ matrix.os }}-${{ matrix.python-version }}/*.whl
          asset_name: sagepy-connector-${{ matrix.os }}-${{ matrix.python-version }}.whl
          asset_content_type: application/zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sagepy-wheel-${{ matrix.os }}-${{ matrix.python-version }}/*.whl
          asset_name: sagepy-${{ matrix.os }}-${{ matrix.python-version }}.whl
          asset_content_type: application/zip